name: Docs

# Generate the documentation on all merges to main, all pull requests, or by
# manual workflow dispatch. The build job can be used as a CI check that the
# docs still build successfully. The deploy job which moves the generated
# html to the gh-apges branch and triggers a GitHub pages deployment
# only runs when a tag is pushed or when the workflow is manually dispatched
# from the main branch.
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
    
# Cancel any in-progress runs if a new run is triggered for the same ref,
# except for tags and main branch pushes.
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && github.ref_type != 'tag' }}

jobs:
  build_sphinx_docs:
    name: Build Sphinx Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true # Enable automatic checkout of all submodules
          fetch-tags: true # For determining the latest tag in conf.py

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    
      - name: Setup DocFX
        run: pixi run setup-dotnet

      - name: Check external links
        run: pixi run linkcheck

      - name: Build documentation
        run: pixi run build

      - name: Upload the content for deployment
        uses: actions/upload-artifact@v7
        with:
          name: docs
          path: ./docs/

  deploy_sphinx_docs:
    name: Deploy Sphinx Docs
    needs: build_sphinx_docs
    permissions:
      contents: write
    if: |
      (github.event_name == 'push' && github.ref_type == 'tag') ||
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Clear previous build if present
        shell: bash
        run: rm -rf ./docs/

      - name: Download the content for deployment
        uses: actions/download-artifact@v8
        with:
          name: docs
          path: ./docs/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dirhtml/